spring:
  application:
    name: "TestProject"
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 5656

logging:
  level:
    root: INFO

#jwt
jwt:
  secret: "bWJhbmstdGVzdC1wcm9qZWN0LXNlY3JldC1rZXkgbWV0YSBtYWluIGNoYW5uZWwgY29tcGxleCBpc3N1ZXMu"
  lifetime: "5m"